### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by jonhoo**
It'd be awesome if we could do a quick point release with this change too!

### CODE REVIEW

**Comment by jcreekmore** [comment]
Looks like that version of nix isn't supported on 1.24.1. If you want to bump the minimum version of Rust required for that version of nix in the travis config, I will merge and do a release.

**Comment by jonhoo** [comment]
Done!

**Review by jcreekmore — APPROVED** [review]

**Comment by jcreekmore** [comment]
Release 0.3.0.

**Comment by jonhoo** [comment]
Looks like nix has received yet another version bump to `0.17`. Low priority bump, but just so you're aware :sweat_smile:

**Pull request merged**
